### ISSUE TITLE
Team Manager Sign Up Page

### ISSUE THREAD

**Issue by m-heck** [m-heck/ProjectManagementApp#4]
Team manager sets up account. Team manager is associated with a specific “Team”

The team manager is also a user, so the same information should be collected:
* Name
* Display Name
* Contact information
* Used for login
    * Username/email
    * Password

Additional information needs to be collected about the team manager that doesn't have to be collected about users:
* Team manager chooses team name (different from manager name)
* Team manager receives OR chooses a Team password/code that people can use to join the manager’s team

OPTIONAL:
We can have "User Sign Up" and "Team Manager Sign Up" buttons or we can have one sign up page, but let team managers check a check box where they enter additional information about their team.

**Comment by mxhng** [comment]
Made team leader login and sign-up page. Team leader sign-up requires a unique team ID.

**Comment by m-heck** [comment]
No need for a display name, just using normal name
